server:
  port: 8080
#  servlet:
#    context-path: /test

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #Show sql logs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
